### ISSUE TITLE
页面太长，截图是空白

### ISSUE THREAD

**Issue by JustinYi922** [lvjinpeng0/screenshot-node#1]
我实现截图的思路跟你差不多。只是nodejs里面我用了exec。我测试的一个页面长度78000,里面都是图片。然后截图出来的jpg 0KB。
我设置了截图区域，30000的高度，可以截图成功，jpg的图片大小是1.4MB。如果是78000。那岂不是更大。怎么设置render的超时时间或者其他的设置来解决这个问题吗？
好苦恼~

**Comment by lvjinpeng0** [comment]
@JustinYi922 你想解决的是什么问题呢？是图片太大还是？

**Comment by JustinYi922** [comment]
@lvjinpeng0 图片很长很长的。

**Comment by lvjinpeng0** [comment]
@JustinYi922 我这个的代码中是利用了`document.body.scrollHeight`来获取页面内容的高度，再用`setInterval`模拟用户向下滚动页面，是为了应对有的页面会设置懒加载。这样的话，最后截图的高度会与页面内容的高度等同，这样的话会满足你的需求么？你是想截图整个页面，还是要再短一点呢？

**Comment by lvjinpeng0** [comment]
@JustinYi922 帅哥，这个还有问题不，没问题我关了啊。近期准备把这个搞成一个可配置的node_modules，如果有需要可以关注下。多谢支持。

**Comment by JustinYi922** [comment]
@lvjinpeng0 关了吧。谢谢了哈。
